### PR TITLE
modified 5.1matrix to suit mw_malloc2d

### PR DESCRIPTION
**Pull request by kaushikvelusamy**
In continuation to https://github.com/emusolutions/emu-issue-tracking/issues/60 and https://github.com/wohlbier/4.1_repl_class

### CODE REVIEW

**Comment by kaushikvelusamy** [comment]
I will update this again with the "Expected migration, cause and memory map" and replace allocRow to AllocRows in my next commit here.

**Comment by wohlbier** [comment]
It occurred to me that we might substantially improve the 6_llt migration pattern, even though I had thought maybe not when we were discussing it. The hundreds of ping-pongs through nodelet zero are at least partially due to the allocation spawns. Looking forward to seeing the results.

**Comment by kaushikvelusamy** [comment]
modified 5.1matrix to suit the latest version of mw_malloc2d in 4.1repl_class

**Comment by wohlbier** [comment]
Nice work Kaushik!

**Pull request merged**
